module.exports = [
  "Sector 70, Neharpar",
  "Sector 86",
  "Ashoka Enclave",
  "Sector 82",
  "Sector 21C",
  "Sector 83",
  "Sector 21A",
  "Sector 80",
  "Ashoka Enclave Part 1",
  "Sector 81",
  "Sector 75",
  "Neharpar, Greater",
  "Sector 21D",
  "Sector 76",
  "Sector 78",
  "Sainik Colony",
  "Sector 49",
  "Sector 77",
  "Sector 85",
  "Sector 88",
  "Mujesar",
  "Sector 72",
  "Sector 79",
  "Sector 9",
  "Nav Durga Vihar, Dayal Bagh Colony",
  "Charmwood Village",
  "Ashoka Enclave Part 3",
  "Sector 87",
  "Inder Colony, Sector 31",
  "Sector 84",
  "Sector 21B",
  "Sector 28",
  "New Industrial Township",
  "Dabua Colony",
  "Greenfield Colony",
  "Sector 11",
  "Sector 55",
  "Sector 3",
  "Sector 6",
  "Sector 37",
  "Jawahar Colony",
  "Sector 45",
  "Sector 31",
  "Lakkarpur",
  "Sector 22",
  "Gurukul Basti",
  "HBH Colony, Sector 28",
  "Sector 16",
  "Jalvayu Vihar, Atmadpur Village",
  "Sector 44",
  "Sector 17",
  "Sector 38",
  "Sector 27",
  "Sector 10",
  "Sector 15",
  "NIT 2",
  "NIT 5",
  "NIT 1",
  "NIT 3",
  "Sector 29",
  "Sector 46",
  "Sector 5",
  "Sector 14",
  "Sector 7",
  "Sector 64",
  "Sector 2",
  "Sector 18",
  "Sector 19",
  "Sector 30",
  "Springfield Colony",
  "Sector 4",
  "Sector 62",
  "Dayal Bagh Colony",
  "Sector 27D",
  "Sector 39",
  "Aitmadpur, Sector 33",
  "Sector 74",
  "Sector 32",
  "Sector 8",
  "Green Field Colony",
  "Mewla Maharajpur, Sector 46"
];
